/* eslint-disable import/no-anonymous-default-export */
export default {
    COMMUNITY_CHAT:"COMMUNITY_CHAT",
    USER_CONNECTED:"USER_CONNECTED",
    MESSAGE_RECEIVED:"MESSAGE_RECEIVED",
    MESSAGE_SENT:"MESSAGE_SENT",
    USER_DISCONNECTED:"USER_DISCONNECTED",
    TYPING:"TYPING",
    VERIFY_USER:"VERIFY_USER",
    LOGON:"LOGON",
    LOGOUT:"LOGOUT",
    PRICATE_MESSAGE:"PRIVATE_MESSAGE"
}